<a href="https://colab.research.google.com/github/YashRudrarap/YashRudrarap/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
age = np.array([24,28,32,34,36])
age

array([24, 28, 32, 34, 36])

In [6]:
data = np.array([[24,12,123,43],[23,34,45,56],[87,79,99,90],[31,34,54,56],[45,54,65,56]])
data

array([[ 24,  12, 123,  43],
       [ 23,  34,  45,  56],
       [ 87,  79,  99,  90],
       [ 31,  34,  54,  56],
       [ 45,  54,  65,  56]])

In [7]:
data[ : , 0:1]

array([[24],
       [23],
       [87],
       [31],
       [45]])

In [9]:
data[0:1 , :]

array([[ 24,  12, 123,  43]])

In [10]:
data[2,3]

np.int64(90)

In [12]:
data[0:2, :]

array([[ 24,  12, 123,  43],
       [ 23,  34,  45,  56]])

In [13]:
data[: ,0:2]

array([[24, 12],
       [23, 34],
       [87, 79],
       [31, 34],
       [45, 54]])

In [16]:
np.mean(data[ : , 0:2])


print("Mean:", np.mean(data[ : , 0:2]))
print("Median:",np.median(data[ : , 0:2]))
print("Standard deviation:",np.std(data[ : , 0:2]))
print("Variance:",np.var(data[ : , 0:2]))

Mean: 42.3
Median: 34.0
Standard deviation: 23.195042573791497
Variance: 538.01


In [22]:
x1 = np.random.randint(15,16, size=7)
x1

array([15, 15, 15, 15, 15, 15, 15])

In [23]:
x1.ndim

1

In [25]:
x2 = np.random.randint(1,20, size=(5,4))
x2

array([[10, 16,  3, 12],
       [19,  9, 17, 17],
       [ 1,  4,  3, 18],
       [ 9, 18,  3,  8],
       [15,  7, 12,  7]])

In [26]:
x3 = np.random.randint(1,20, size=(5,4,3))
x3

array([[[ 7, 11,  2],
        [13, 12, 18],
        [ 6,  6, 15],
        [12, 10, 15]],

       [[ 3, 15, 10],
        [ 9,  5, 19],
        [ 7, 14,  2],
        [ 6, 14, 18]],

       [[18, 11, 15],
        [ 2,  4,  7],
        [ 9, 12, 18],
        [17, 12,  2]],

       [[ 8,  6,  8],
        [ 5, 12, 15],
        [15, 18, 18],
        [14, 15,  8]],

       [[ 5,  8, 14],
        [ 9, 17, 10],
        [ 8, 11,  8],
        [11, 10,  2]]])

In [28]:
print("Mean:", df["BP"].mean())
print("Median:",df["BP"].median())
print("Standard deviation:",np.std(data[ : , 0:2]))
print("Variance:",np.var(data[ : , 0:2]))

NameError: name 'df' is not defined

In [29]:
import numpy as np
import pandas as pd


data = np.array([
    [120, 170, 65],
    [130, 175, 70],
    [110, 165, 60],
    [140, 180, 80],
    [125, 172, 68]
])


In [30]:
df = pd.DataFrame(data, columns=['Blood Pressure', 'Height', 'Weight'])


In [31]:
mean = df.mean()
median = df.median()
variance = df.var()
std_dev = df.std()


In [32]:
stats_table = pd.DataFrame([
    mean,
    median,
    variance,
    std_dev
], index=['a', 'b', 'c', 'd'])

print(stats_table)

   Blood Pressure     Height     Weight
a       125.00000  172.40000  68.600000
b       125.00000  172.00000  68.000000
c       125.00000   31.30000  54.800000
d        11.18034    5.59464   7.402702


student marks obseravtion :


In [33]:
import pandas as pd

unstructured_data = [
    ["John", 88, "A", 3],
    ["Anika", 92, "B", 1],
    ["Ravi", 85, "A", 4],
    ["Sara", 90, "B", 2],
    ["Mike", 76, "C", 5]
]


In [35]:

df = pd.DataFrame(unstructured_data, columns=["Student Name", "Marks", "Section", "Rank"])

print(df)


  Student Name  Marks Section  Rank
0         John     88       A     3
1        Anika     92       B     1
2         Ravi     85       A     4
3         Sara     90       B     2
4         Mike     76       C     5


In [36]:
df_sorted = df.sort_values(by="Rank")
print(df_sorted)


  Student Name  Marks Section  Rank
1        Anika     92       B     1
3         Sara     90       B     2
0         John     88       A     3
2         Ravi     85       A     4
4         Mike     76       C     5
